<template>
  <div class="preview-page">
    <div class="page-header">
      <h1>Report Preview</h1>
      <p class="page-subtitle">Preview of your TOE Description report</p>
      <div class="preview-actions">
        <button @click="refreshPreview" class="refresh-button">
          🔄 Refresh
        </button>
        <button @click="exportToPDF" class="export-button">
          📄 Export PDF
        </button>
      </div>
    </div>

    <div v-if="loading" class="loading-state">
      <div class="loading-spinner">⏳</div>
      <p>Loading report data...</p>
    </div>

    <div v-else-if="!toeData" class="empty-state">
      <div class="empty-icon">📋</div>
      <h3>No Report Data</h3>
      <p>Please fill out the TOE Description form first.</p>
      <router-link to="/documentation/toe-description" class="fill-form-button">
        Fill TOE Description Form
      </router-link>
    </div>

    <div v-else class="preview-container">
      <!-- Report Header -->
      <div class="report-header">
        <h1 class="report-title">Target of Evaluation (TOE) Description</h1>
        <div class="report-meta">
          <p><strong>Generated:</strong> {{ new Date().toLocaleDateString() }}</p>
          <p><strong>Version:</strong> {{ toeData.toe_version || 'Not specified' }}</p>
        </div>
      </div>

      <!-- Report Content -->
      <div class="report-content">
        <!-- Basic Information -->
        <section class="report-section">
          <h2>Basic Information</h2>
          <div class="info-grid">
            <div class="info-item">
              <label>TOE Name:</label>
              <span>{{ toeData.toe_name || 'Not specified' }}</span>
            </div>
            <div class="info-item">
              <label>TOE Vendor:</label>
              <span>{{ toeData.toe_vendor || 'Not specified' }}</span>
            </div>
            <div class="info-item">
              <label>Evaluation Date:</label>
              <span>{{ toeData.evaluation_date || 'Not specified' }}</span>
            </div>
            <div class="info-item">
              <label>TOE Version:</label>
              <span>{{ toeData.toe_version || 'Not specified' }}</span>
            </div>
            <div class="info-item">
              <label>Common Criteria Version:</label>
              <span>{{ toeData.common_criteria_version || 'Not specified' }}</span>
            </div>
            <div class="info-item">
              <label>Laboratory Name:</label>
              <span>{{ toeData.laboratory_name || 'Not specified' }}</span>
            </div>
          </div>
        </section>

        <!-- Laboratory Information -->
        <section class="report-section" v-if="toeData.laboratory_address">
          <h2>Laboratory Information</h2>
          <div class="content-block">
            <h3>Laboratory Address</h3>
            <div class="address-block">{{ toeData.laboratory_address }}</div>
          </div>
        </section>

        <!-- Vendor Information -->
        <section class="report-section" v-if="toeData.vendor_address">
          <h2>Vendor Information</h2>
          <div class="content-block">
            <h3>Vendor Address</h3>
            <div class="rich-content" v-html="sanitizeHtml(toeData.vendor_address)"></div>
          </div>
        </section>

        <!-- Evaluation Personnel -->
        <section class="report-section" v-if="toeData.evaluation_personnel">
          <h2>Evaluation Personnel</h2>
          <div class="content-block">
            <div class="rich-content" v-html="sanitizeHtml(toeData.evaluation_personnel)"></div>
          </div>
        </section>

        <!-- Protection Profile Module -->
        <section class="report-section" v-if="toeData.protection_profile_module">
          <h2>Protection Profile Module</h2>
          <div class="content-block">
            <div class="rich-content" v-html="sanitizeHtml(toeData.protection_profile_module)"></div>
          </div>
        </section>

        <!-- TOE Description -->
        <section class="report-section" v-if="toeData.toe_description">
          <h2>TOE Description</h2>
          <div class="content-block">
            <div class="rich-content" v-html="sanitizeHtml(toeData.toe_description)"></div>
          </div>
        </section>
      </div>

      <!-- Report Footer -->
      <div class="report-footer">
        <p><em>This report was generated by the NGEAICC platform on {{ new Date().toLocaleString() }}</em></p>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { ref, onMounted } from 'vue'
import ApiService, { type TOEDescription } from '../services/api'

const toeData = ref<TOEDescription | null>(null)
const loading = ref(false)

onMounted(() => {
  loadTOEData()
})

const loadTOEData = async () => {
  loading.value = true
  try {
    const data = await ApiService.getTOEDescription()
    toeData.value = data
  } catch (error) {
    console.error('Error loading TOE data:', error)
  } finally {
    loading.value = false
  }
}

const refreshPreview = () => {
  loadTOEData()
}

const exportToPDF = () => {
  // For now, just print the page
  window.print()
}

// Basic HTML sanitization (in a real app, use a proper sanitization library)
const sanitizeHtml = (html: string): string => {
  if (!html) return ''
  
  // Allow basic formatting tags but remove potentially dangerous ones
  const allowedTags = ['p', 'br', 'strong', 'b', 'em', 'i', 'u', 'ul', 'ol', 'li', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'blockquote']
  
  // This is a very basic sanitization - in production, use DOMPurify or similar
  let sanitized = html
  
  // Remove script tags
  sanitized = sanitized.replace(/<script\b[^<]*(?:(?!<\/script>)<[^<]*)*<\/script>/gi, '')
  
  // Remove on* attributes
  sanitized = sanitized.replace(/\s*on\w+="[^"]*"/gi, '')
  
  return sanitized
}
</script>

<style scoped>
.preview-page {
  max-width: 1200px;
  margin: 0 auto;
}

.page-header {
  margin-bottom: 2rem;
  display: flex;
  justify-content: space-between;
  align-items: flex-start;
}

.page-header h1 {
  font-size: 2rem;
  font-weight: 700;
  color: #1f2937;
  margin-bottom: 0.5rem;
}

.page-subtitle {
  color: #6b7280;
  font-size: 1.1rem;
  margin: 0;
}

.preview-actions {
  display: flex;
  gap: 1rem;
}

.refresh-button, .export-button {
  padding: 0.5rem 1rem;
  border: 1px solid #d1d5db;
  border-radius: 0.375rem;
  background: white;
  cursor: pointer;
  font-size: 0.875rem;
  font-weight: 500;
  transition: all 0.15s ease;
}

.refresh-button:hover, .export-button:hover {
  background: #f9fafb;
  border-color: #9ca3af;
}

.export-button {
  background: #3498db;
  color: white;
  border-color: #3498db;
}

.export-button:hover {
  background: #2980b9;
  border-color: #2980b9;
}

.loading-state, .empty-state {
  text-align: center;
  padding: 4rem 2rem;
  background: white;
  border-radius: 0.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
}

.loading-spinner, .empty-icon {
  font-size: 3rem;
  margin-bottom: 1rem;
}

.empty-state h3 {
  color: #374151;
  margin-bottom: 1rem;
}

.empty-state p {
  color: #6b7280;
  margin-bottom: 2rem;
}

.fill-form-button {
  background: #3498db;
  color: white;
  padding: 0.75rem 1.5rem;
  border-radius: 0.375rem;
  text-decoration: none;
  font-weight: 500;
  display: inline-block;
  transition: background-color 0.15s ease;
}

.fill-form-button:hover {
  background: #2980b9;
}

.preview-container {
  background: white;
  border-radius: 0.5rem;
  box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);
  overflow: hidden;
}

.report-header {
  padding: 2rem;
  background: #f8f9fa;
  border-bottom: 1px solid #e5e7eb;
}

.report-title {
  font-size: 1.75rem;
  font-weight: 700;
  color: #1f2937;
  margin-bottom: 1rem;
}

.report-meta {
  display: flex;
  gap: 2rem;
  color: #6b7280;
  font-size: 0.875rem;
}

.report-meta p {
  margin: 0;
}

.report-content {
  padding: 2rem;
}

.report-section {
  margin-bottom: 3rem;
}

.report-section:last-child {
  margin-bottom: 0;
}

.report-section h2 {
  font-size: 1.25rem;
  font-weight: 600;
  color: #374151;
  margin-bottom: 1.5rem;
  padding-bottom: 0.5rem;
  border-bottom: 2px solid #e5e7eb;
}

.info-grid {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(300px, 1fr));
  gap: 1rem;
}

.info-item {
  padding: 1rem;
  background: #f9fafb;
  border-radius: 0.375rem;
  border: 1px solid #e5e7eb;
}

.info-item label {
  display: block;
  font-weight: 500;
  color: #374151;
  margin-bottom: 0.25rem;
  font-size: 0.875rem;
}

.info-item span {
  color: #1f2937;
  font-size: 0.9rem;
}

.content-block {
  margin-bottom: 2rem;
}

.content-block h3 {
  font-size: 1rem;
  font-weight: 500;
  color: #374151;
  margin-bottom: 1rem;
}

.address-block {
  background: #f9fafb;
  border: 1px solid #e5e7eb;
  border-radius: 0.375rem;
  padding: 1rem;
  white-space: pre-wrap;
  font-family: 'Inter', sans-serif;
  color: #1f2937;
}

.rich-content {
  background: #f9fafb;
  border: 1px solid #e5e7eb;
  border-radius: 0.375rem;
  padding: 1rem;
  font-family: 'Inter', sans-serif;
  line-height: 1.6;
}

.rich-content :deep(h1),
.rich-content :deep(h2),
.rich-content :deep(h3),
.rich-content :deep(h4),
.rich-content :deep(h5),
.rich-content :deep(h6) {
  margin-top: 1.5rem;
  margin-bottom: 1rem;
  font-weight: 600;
}

.rich-content :deep(p) {
  margin-bottom: 1rem;
}

.rich-content :deep(ul),
.rich-content :deep(ol) {
  margin-bottom: 1rem;
  padding-left: 1.5rem;
}

.rich-content :deep(li) {
  margin-bottom: 0.5rem;
}

.rich-content :deep(blockquote) {
  border-left: 4px solid #3498db;
  padding-left: 1rem;
  margin: 1rem 0;
  font-style: italic;
  color: #6b7280;
}

.report-footer {
  padding: 1rem 2rem;
  background: #f8f9fa;
  border-top: 1px solid #e5e7eb;
  text-align: center;
  color: #6b7280;
  font-size: 0.875rem;
}

/* Print styles */
@media print {
  .page-header {
    display: none;
  }
  
  .preview-container {
    box-shadow: none;
    border: none;
  }
  
  .report-header {
    background: white;
    border-bottom: 2px solid #000;
  }
  
  .report-footer {
    background: white;
    border-top: 2px solid #000;
  }
}

/* Responsive design */
@media (max-width: 768px) {
  .page-header {
    flex-direction: column;
    align-items: flex-start;
  }

  .preview-actions {
    margin-top: 1rem;
  }

  .report-meta {
    flex-direction: column;
    gap: 0.5rem;
  }

  .info-grid {
    grid-template-columns: 1fr;
  }
}
</style>